name: Track Daily Unique Views

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:      # manual run possible

permissions:
  contents: write

jobs:
  update-uniques:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Ensure traffic.json exists
        run: |
          if [ ! -f .github/traffic.json ]; then
            cat > .github/traffic.json <<'JSON'
{
  "total_daily_uniques_sum": 0,
  "last_processed": "1970-01-01T00:00:00Z"
}
JSON
            git add .github/traffic.json
            git commit -m "Create initial traffic.json" || echo "no changes"
            git push || echo "push failed (you may push manually)"
          fi

      - name: Fetch current traffic from GitHub API
        id: fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          echo "Fetching traffic for $REPO"

          VIEWS_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/traffic/views")

          echo "$VIEWS_JSON" > /tmp/views.json
          echo "views<<'JSON'" >> $GITHUB_OUTPUT
          cat /tmp/views.json >> $GITHUB_OUTPUT
          echo "JSON" >> $GITHUB_OUTPUT

      - name: Compute new daily uniques since last_processed and update file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LAST=$(jq -r '.last_processed' .github/traffic.json)
          echo "Last processed: $LAST"

          VIEWS_JSON="${{ steps.fetch.outputs.views }}"

          if [ -z "$VIEWS_JSON" ] || [ "$VIEWS_JSON" = "null" ]; then
            echo "No views data returned. Exiting."
            exit 0
          fi

          new_uniques=$(jq --arg last "$LAST" '[.views[] | select(.timestamp > $last) | .uniques] | add // 0' <<<"$VIEWS_JSON")
          echo "New daily-uniques to add: $new_uniques"

          newest_ts=$(jq -r '[.views[] | .timestamp] | max // empty' <<<"$VIEWS_JSON")
          if [ -z "$newest_ts" ]; then
            NEW_LAST="$LAST"
          else
            NEW_LAST="$newest_ts"
          fi

          echo "New last_processed will be: $NEW_LAST"

          tmp=$(mktemp)
          jq --argjson nu "$new_uniques" --arg newlast "$NEW_LAST" \
            '.total_daily_uniques_sum += ($nu // 0) | .last_processed = $newlast' \
            .github/traffic.json > "$tmp" && mv "$tmp" .github/traffic.json

          cat .github/traffic.json

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/traffic.json
          git diff --staged --quiet || git commit -m "Update daily-unique totals (+$new_uniques) and last_processed" || echo "nothing to commit"
          git push origin HEAD:${{ github.ref_name }} || echo "Push failed (check permissions)"
